perl: use GPL-1.0-or-later instead of obsolete GPL-1.0+
* fixes:
  https://github.com/shift-left-test/meta-shift/issues/7

  ERROR: libcanary-stability-perl-2013-r0 do_package_qa: QA Issue: Recipe LICENSE includes obsolete licenses GPL-1.0+ [obsolete-license]
  ERROR: libtypes-serialiser-perl-1.01-r0 do_package_qa: QA Issue: Recipe LICENSE includes obsolete licenses GPL-1.0+ [obsolete-license]
  ERROR: libcommon-sense-perl-3.75-r0 do_package_qa: QA Issue: Recipe LICENSE includes obsolete licenses GPL-1.0+ [obsolete-license]

* perl license was updated in oe-core in:
  https://git.openembedded.org/openembedded-core/commit/?id=ceda3238cdbf1beb216ae9ddb242470d5dfc25e0

Signed-off-by: Martin Jansa <martin2.jansa@lgepartner.com>